import { GEOMETRY, MATERIAL } from './types';

const defaultModels = {
  [GEOMETRY.Text3D]: {
    uuid: null,
    name: 'text3d',
    geometry: GEOMETRY.Text3D,
    material: MATERIAL.Normal,
    color: '#00ff00',
    text: 'text3d',
    args: [1, 1, 1],
    scale: 1,
    position: [0, 0, 0],
    rotationDeg: [0, 0, 0],
    rotationRad: [0, 0, 0],
  },
  [GEOMETRY.Text]: {
    uuid: null,
    name: 'text',
    geometry: GEOMETRY.Text,
    material: MATERIAL.Standard,
    color: '#aaaaaa',
    text: 'text',
    args: [1, 1, 1],
    scale: 1,
    position: [0, 0, 0],
    rotationDeg: [0, 0, 0],
    rotationRad: [0, 0, 0],
  },
  [GEOMETRY.Box]: {
    uuid: null,
    name: 'box',
    geometry: GEOMETRY.Box,
    material: MATERIAL.Standard,
    color: '#10b981',
    text: 'text',
    args: [1, 2, 1],
    scale: 1,
    position: [0, 0, 0],
    rotationDeg: [0, 0, 0],
    rotationRad: [0, 0, 0],
  },
  [GEOMETRY.Sphere]: {
    uuid: null,
    name: 'sphere',
    geometry: GEOMETRY.Sphere,
    material: MATERIAL.Normal,
    color: '#10b981',
    text: 'text',
    args: [1, 32, 16],
    scale: 1,
    position: [0, 0, 0],
    rotationDeg: [0, 0, 0],
    rotationRad: [0, 0, 0],
  },
  [GEOMETRY.Cone]: {
    uuid: null,
    name: 'cone',
    geometry: GEOMETRY.Cone,
    material: MATERIAL.Normal,
    color: '#10b981',
    text: 'text',
    args: [1, 2, 32],
    scale: 1,
    position: [0, 0, 0],
    rotationDeg: [0, 0, 0],
    rotationRad: [0, 0, 0],
  },
};

export default defaultModels;
