export const AXIS = {
  X: 0,
  Y: 1,
  Z: 2,
};

export const MATERIAL = {
  Normal: 'Normal',
  Phong: 'Phong',
  Standard: 'Standard',
  Basic: 'Basic',
  Toon: 'Toon',
};

export const GEOMETRY = {
  Text3D: 'Text3D',
  Text: 'Text',
  Box: 'Box',
  Sphere: 'Sphere',
  Cone: 'Cone',
};

export const ACTION = {
  ADD_OBJECT: 'ADD_OBJECT',
  DELETE_OBJECT: 'DELETE_OBJECT',
  DUPLICATE_OBJECT: 'DUPLICATE_OBJECT',
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_GEOMETRY: 'CHANGE_GEOMETRY',
  CHANGE_MATERIAL: 'CHANGE_MATERIAL',
  CHANGE_COLOR: 'CHANGE_COLOR',
  CHANGE_TEXT: 'CHANGE_TEXT',
  CHANGE_ARGS: 'CHANGE_ARGS',
  CHANGE_SCALE: 'CHANGE_SCALE',
  CHANGE_POSITION: 'CHANGE_X_POSITION',

  CHANGE_ROTATION: 'CHANGE_ROTATION',
};

export const SCENE_ACTION = {
  BACKGROUND_COLOR: 'BACKGROUND_COLOR',
  SHOW_GRID: 'SHOW_GRID',
  GRID_SIZE: 'GRID_SIZE',
  GRID_INFINITE: 'GRID_INFINITE',
  GRID_CELL_COLOR: 'GRID_CELL_COLOR',
  GRID_SECTION_COLOR: 'GRID_SECTION_COLOR',
  GRID_FADE_DISTANCE: 'GRID_FADE_DISTANCE',
};
