export const AXIS = {
  X: 0,
  Y: 1,
  Z: 2,
};

export const MATERIAL = {
  PHONG: 'PHONG',
  BASIC: 'BASIC',
  NORMAL: 'NORMAL',
  TOON: 'TOON',
  STANDARD: 'STANDARD',
};

export const GEOMETRY = {
  TEXT3D: 'TEXT3D',
  TEXT2D: 'TEXT2D',
  BOX: 'BOX',
  SPHERE: 'SPHERE',
  CONE: 'CONE',
};

export const ACTION = {
  ADD_OBJECT: 'ADD_OBJECT',
  DELETE_OBJECT: 'DELETE_OBJECT',
  DUPLICATE_OBJECT: 'DUPLICATE_OBJECT',
  CHANGE_GEOMETRY: 'CHANGE_GEOMETRY',
  CHANGE_MATERIAL: 'CHANGE_MATERIAL',
  CHANGE_COLOR: 'CHANGE_COLOR',
  CHANGE_TEXT: 'CHANGE_TEXT',
  CHANGE_ARGS: 'CHANGE_ARGS',
  CHANGE_SCALE: 'CHANGE_SCALE',
  CHANGE_POSITION: 'CHANGE_X_POSITION',

  CHANGE_ROTATION: 'CHANGE_ROTATION',
};
